spring.application.name=sea-island-lottery
#thymeleaf
spring.thymeleaf.prefix=file:src/main/resources/templates/
#H2DB
spring.datasource.data-source-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testDB;DB_CLOSE_ON_EXIT=TRUE;MODE=MySQL
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create
