spring.application.name=sea-island-lottery
#thymeleaf
spring.thymeleaf.prefix=file:src/main/resources/templates/
#Supabase DB
spring.datasource.url=jdbc:postgresql://db.xqxamvgkzuxeyyvmkllv.supabase.co:5432/postgres?user=postgres&password=1067supabase-E233
spring.datasource.username=postgres
spring.datasource.password=1067supabase-E233
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# SQL Initialization
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
# Renderポート用指定
server.port=${PORT:8080}